from __future__ import annotations

from app.config import get_settings
from app.schemas import SourceCatalogEntry


def build_source_catalog() -> list[SourceCatalogEntry]:
    settings = get_settings()
    return [
        SourceCatalogEntry(
            key="kap_disclosures",
            label="KAP Disclosures",
            channel="official",
            authority_level="authoritative",
            asset_scope="bist",
            legal_mode="strict_api_or_low_rate_crawl",
            freshness_slo_seconds=300,
            rate_limit_seconds=4.0,
            ticker_resolution_method="symbol_page_and_disclosure_mapping",
            enabled=True,
            enabled_by_default=True,
            retention_tier="permanent",
            notes="Ground truth for official company disclosures.",
        ),
        SourceCatalogEntry(
            key="bist_universe",
            label="Borsa Istanbul Universe",
            channel="official",
            authority_level="authoritative",
            asset_scope="bist",
            legal_mode="open_first",
            freshness_slo_seconds=86400,
            rate_limit_seconds=30.0,
            ticker_resolution_method="exchange_symbol_registry",
            enabled=True,
            enabled_by_default=True,
            retention_tier="permanent",
            notes="Universe refresh and exchange context.",
        ),
        SourceCatalogEntry(
            key="tcmb_macro",
            label="TCMB EVDS",
            channel="official",
            authority_level="authoritative",
            asset_scope="macro",
            legal_mode="api_key_optional",
            freshness_slo_seconds=1800,
            rate_limit_seconds=10.0,
            ticker_resolution_method="macro_context_only",
            enabled=bool(settings.tcmb_evds_api_key),
            enabled_by_default=False,
            retention_tier="permanent",
            notes="Macro context layer; disabled without EVDS key.",
        ),
        SourceCatalogEntry(
            key="market_prices",
            label="Market Price Feed",
            channel="market",
            authority_level="context_only",
            asset_scope="bist",
            legal_mode="open_first_with_cache",
            freshness_slo_seconds=60,
            rate_limit_seconds=2.0,
            ticker_resolution_method="ticker_suffix_mapping",
            enabled=True,
            enabled_by_default=True,
            retention_tier="permanent",
            notes="Near-real-time price context via yfinance primary and cache fallback.",
        ),
        SourceCatalogEntry(
            key="company_ir_pages",
            label="Company Investor Relations",
            channel="official",
            authority_level="official_context",
            asset_scope="bist",
            legal_mode="allowlist_only",
            freshness_slo_seconds=3600,
            rate_limit_seconds=8.0,
            ticker_resolution_method="issuer_domain_allowlist",
            enabled=True,
            enabled_by_default=True,
            retention_tier="permanent",
            notes="Issuer-owned pages used only as supporting official context.",
        ),
        SourceCatalogEntry(
            key="aa_rss",
            label="AA Ekonomi RSS",
            channel="media",
            authority_level="tier1_media",
            asset_scope="bist",
            legal_mode="rss",
            freshness_slo_seconds=60,
            rate_limit_seconds=4.0,
            ticker_resolution_method="alias_and_entity_resolution",
            enabled=True,
            enabled_by_default=True,
            retention_tier="permanent",
            notes="Narrative feed used after entity verification.",
        ),
        SourceCatalogEntry(
            key="bloomberght_rss",
            label="Bloomberg HT RSS",
            channel="media",
            authority_level="tier1_media",
            asset_scope="bist",
            legal_mode="rss",
            freshness_slo_seconds=60,
            rate_limit_seconds=4.0,
            ticker_resolution_method="alias_and_entity_resolution",
            enabled=True,
            enabled_by_default=True,
            retention_tier="permanent",
            notes="Tier-1 media narrative layer.",
        ),
        SourceCatalogEntry(
            key="paraanaliz_rss",
            label="ParaAnaliz RSS",
            channel="media",
            authority_level="narrative",
            asset_scope="bist",
            legal_mode="rss",
            freshness_slo_seconds=120,
            rate_limit_seconds=4.0,
            ticker_resolution_method="alias_and_entity_resolution",
            enabled=True,
            enabled_by_default=True,
            retention_tier="permanent",
            notes="Secondary Turkish finance feed.",
        ),
        SourceCatalogEntry(
            key="ekonomim_rss",
            label="Ekonomim RSS",
            channel="media",
            authority_level="tier1_media",
            asset_scope="bist",
            legal_mode="rss",
            freshness_slo_seconds=60,
            rate_limit_seconds=4.0,
            ticker_resolution_method="alias_and_entity_resolution",
            enabled=True,
            enabled_by_default=True,
            retention_tier="permanent",
            notes="Economy-focused Turkish media feed with entity verification.",
        ),
        SourceCatalogEntry(
            key="bigpara_rss",
            label="Bigpara RSS",
            channel="media",
            authority_level="narrative",
            asset_scope="bist",
            legal_mode="rss",
            freshness_slo_seconds=90,
            rate_limit_seconds=4.0,
            ticker_resolution_method="alias_and_entity_resolution",
            enabled=True,
            enabled_by_default=True,
            retention_tier="permanent",
            notes="Broad finance and market feed used after ticker/entity verification.",
        ),
        SourceCatalogEntry(
            key="dunya_rss",
            label="Dünya Gazetesi RSS",
            channel="media",
            authority_level="tier1_media",
            asset_scope="bist",
            legal_mode="rss",
            freshness_slo_seconds=120,
            rate_limit_seconds=4.0,
            ticker_resolution_method="alias_and_entity_resolution",
            enabled=True,
            enabled_by_default=True,
            retention_tier="permanent",
            notes="Business and markets coverage from Dünya.",
        ),
        SourceCatalogEntry(
            key="mynet_finans_rss",
            label="Mynet Finans RSS",
            channel="media",
            authority_level="narrative",
            asset_scope="bist",
            legal_mode="rss",
            freshness_slo_seconds=120,
            rate_limit_seconds=4.0,
            ticker_resolution_method="alias_and_entity_resolution",
            enabled=True,
            enabled_by_default=True,
            retention_tier="permanent",
            notes="Broad finance feed kept behind entity verification.",
        ),
        SourceCatalogEntry(
            key="haberturk_ekonomi_rss",
            label="Habertürk Ekonomi RSS",
            channel="media",
            authority_level="tier1_media",
            asset_scope="bist",
            legal_mode="rss",
            freshness_slo_seconds=120,
            rate_limit_seconds=4.0,
            ticker_resolution_method="alias_and_entity_resolution",
            enabled=True,
            enabled_by_default=True,
            retention_tier="permanent",
            notes="Economy feed used as narrative source after verification.",
        ),
        SourceCatalogEntry(
            key="sozcu_ekonomi_rss",
            label="Sözcü Ekonomi RSS",
            channel="media",
            authority_level="narrative",
            asset_scope="bist",
            legal_mode="rss",
            freshness_slo_seconds=120,
            rate_limit_seconds=4.0,
            ticker_resolution_method="alias_and_entity_resolution",
            enabled=True,
            enabled_by_default=True,
            retention_tier="permanent",
            notes="Supplementary economy feed with strict entity filtering.",
        ),
        SourceCatalogEntry(
            key="foreks_rss",
            label="Foreks RSS",
            channel="media",
            authority_level="tier1_media",
            asset_scope="bist",
            legal_mode="rss",
            freshness_slo_seconds=60,
            rate_limit_seconds=4.0,
            ticker_resolution_method="alias_and_entity_resolution",
            enabled=True,
            enabled_by_default=True,
            retention_tier="permanent",
            notes="Market-focused feed suitable for ticker-level narrative updates.",
        ),
        SourceCatalogEntry(
            key="investing_tr_news_rss",
            label="Investing.com TR RSS",
            channel="media",
            authority_level="narrative",
            asset_scope="bist",
            legal_mode="rss",
            freshness_slo_seconds=120,
            rate_limit_seconds=4.0,
            ticker_resolution_method="alias_and_entity_resolution",
            enabled=True,
            enabled_by_default=True,
            retention_tier="permanent",
            notes="Additional open news feed used after entity resolution.",
        ),
        SourceCatalogEntry(
            key="google_news_discovery",
            label="Google News Discovery RSS",
            channel="discovery",
            authority_level="discovery_only",
            asset_scope="bist",
            legal_mode="rss_discovery_only",
            freshness_slo_seconds=120,
            rate_limit_seconds=4.0,
            ticker_resolution_method="candidate_then_entity_verify",
            enabled=settings.news_enable_discovery,
            enabled_by_default=False,
            retention_tier="permanent",
            notes="Candidate discovery only; disabled by default in strict demo profile.",
        ),
        SourceCatalogEntry(
            key="web_search_context",
            label="Open Web Research",
            channel="discovery",
            authority_level="discovery_only",
            asset_scope="bist",
            legal_mode="open_search_api_or_fallback",
            freshness_slo_seconds=300,
            rate_limit_seconds=4.0,
            ticker_resolution_method="query_then_entity_verify",
            enabled=bool(settings.web_search_enabled),
            enabled_by_default=True,
            retention_tier="permanent",
            notes="Open web research layer via Tavily or DuckDuckGo fallback. Never authoritative on its own.",
        ),
        SourceCatalogEntry(
            key="eventregistry",
            label="Event Registry",
            channel="media",
            authority_level="premium_media",
            asset_scope="bist",
            legal_mode="paid_api",
            freshness_slo_seconds=60,
            rate_limit_seconds=2.0,
            ticker_resolution_method="entity_api",
            enabled=bool(settings.eventregistry_api_key),
            enabled_by_default=False,
            retention_tier="permanent",
            notes="Optional premium connector.",
        ),
        SourceCatalogEntry(
            key="newsapi_ai",
            label="NewsAPI.ai",
            channel="media",
            authority_level="premium_media",
            asset_scope="bist",
            legal_mode="paid_api",
            freshness_slo_seconds=60,
            rate_limit_seconds=2.0,
            ticker_resolution_method="entity_api",
            enabled=bool(settings.newsapi_ai_key),
            enabled_by_default=False,
            retention_tier="permanent",
            notes="Optional premium connector.",
        ),
        SourceCatalogEntry(
            key="brokerage_uploads",
            label="Brokerage Uploads",
            channel="brokerage",
            authority_level="expert_framing",
            asset_scope="bist",
            legal_mode="manual_upload",
            freshness_slo_seconds=3600,
            rate_limit_seconds=0.0,
            ticker_resolution_method="metadata_and_filename",
            enabled=True,
            enabled_by_default=True,
            retention_tier="permanent",
            notes="Manual URL/PDF ingestion for broker reports.",
        ),
        SourceCatalogEntry(
            key="user_uploads",
            label="User Upload Corpus",
            channel="user",
            authority_level="session_scope",
            asset_scope="workspace",
            legal_mode="local_upload",
            freshness_slo_seconds=0,
            rate_limit_seconds=0.0,
            ticker_resolution_method="explicit_or_detected_ticker",
            enabled=True,
            enabled_by_default=True,
            retention_tier="permanent",
            notes="User-owned session corpus used only when requested.",
        ),
        SourceCatalogEntry(
            key="x_signal",
            label="X Signal Layer",
            channel="social",
            authority_level="signal_only",
            asset_scope="bist",
            legal_mode="official_paid_api_only",
            freshness_slo_seconds=120,
            rate_limit_seconds=3.0,
            ticker_resolution_method="handle_and_entity_resolution",
            enabled=bool(settings.x_api_bearer_token),
            enabled_by_default=False,
            retention_tier="permanent",
            notes="Optional social signal layer; never authoritative.",
        ),
        SourceCatalogEntry(
            key="coingecko_context",
            label="CoinGecko Context",
            channel="crypto",
            authority_level="context_only",
            asset_scope="crypto",
            legal_mode="open_api",
            freshness_slo_seconds=120,
            rate_limit_seconds=3.0,
            ticker_resolution_method="symbol_to_coin_mapping",
            enabled=bool(settings.crypto_context_enabled),
            enabled_by_default=True,
            retention_tier="permanent",
            notes="Primary crypto context connector; kept separate from BIST evidence.",
        ),
        SourceCatalogEntry(
            key="binance_spot_context",
            label="Binance Spot Context",
            channel="crypto",
            authority_level="context_only",
            asset_scope="crypto",
            legal_mode="open_api",
            freshness_slo_seconds=120,
            rate_limit_seconds=2.0,
            ticker_resolution_method="symbol_usdt_mapping",
            enabled=bool(settings.crypto_context_enabled),
            enabled_by_default=True,
            retention_tier="permanent",
            notes="Secondary crypto market context; used as fallback/secondary context only.",
        ),
    ]
